### ISSUE TITLE
doesn't support python3.10.9

### ISSUE THREAD

**Issue by cocowool** [epinna/tplmap#114]
` python3 tplmap.py -u "http://61.147.171.105:55831/info\?file\=a.txt"
Tplmap 0.5
    Automatic Server-Side Template Injection Detection and Exploitation Tool

Testing if GET parameter 'file\' is injectable
Exiting: module 'collections' has no attribute 'Mapping'`

**Comment by cehuda1** [comment]
im too

**Comment by wdearzh** [comment]
edit core/plugin.py and change  "collections.Mapping" to "collections.abc.Mapping"

**Comment by rnocx** [comment]
> edit core/plugin.py and change "collections.Mapping" to "collections.abc.Mapping"

This also works in 3.11

**Comment by 0x25** [comment]
work to the next error 

`Exiting: 'bool' object has no attribute 'replace'`

**Comment by r-erd** [comment]
It might be a good idea to merge this issue with https://github.com/epinna/tplmap/issues/104 if there are no other compatibility issues related to the python version.
